kind: pipeline
type: ssh
name: default

server: 
    host: 165.22.104.56 
    user: root
    ssh_key: 
        from_secret: key002

steps:
- name: auth server
  commands:
    - gcloud config set project zoa001 
    - gcloud auth activate-service-account zoa-service-acct@zoa001.iam.gserviceaccount.com --key-file=/root/secrets/.creds.json
- name: cloudbuild jwt-auth-nodejs-microservice 
  commands:
    - gcloud builds submit
- name: docker compose (deploy)
  commands:
    - cp /root/docker-compose.yml .
    - docker-compose up -d --force-recreate 
- name: slack-success
  commands: 
    - cp /root/slack/message.sh .
    - sh message.sh 
  when: 
    status: 
      - success
      - failure 
