version: "3"
services:
  api-server:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - mongo-server
  mongo-server:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      - MONGO_DATA_DIR=/data/db
      - MONGO_LOG_DIR=/dev/null
    ports:
      - 27017:27017
    volumes:
      - ./data/db:/data/db
    command: mongod --smallfiles --logpath=/dev/null # --quiet
